### ISSUE TITLE
최종보고서 작성

### ISSUE THREAD

**Issue by sonshn** [swengineering7/Book-Shopping-Mall#18]
최종보고서 작성 💡

**Comment by xx10222** [comment]
보고서 2번에 로그인(아이디/비밀번호 찾기), 회원가입(아이디 중복 확인), 마이페이지(정보 수정 및 구매/판매 내역), 관리자 관리페이지 구현 과정 및 기능 작성하겠습니다!

**Comment by justashow** [comment]
제출
