### ISSUE TITLE
전체 회의록

### ISSUE THREAD

**Issue by justashow** [swengineering7/Book-Shopping-Mall#20]
### 3차 프로젝트 전체 회의 내용(진행상황)

**5/12 수요일 회의**
- 개발환경 설정, DB 테이블 작성
- 회원가입 기능, 로그인 기능 구현시작

**5/15 토요일 회의**
- 회원가입 기능, 로그인 기능 관련 피드백
- 상품 추가/수정/삭제 기능 구현 시작

**5/20 목요일 회의**
- 새로운 모듈 사용 제안
- 회원가입 기능, 로그인 기능 구현 마무리
- DB 테이블 수정
- 마이페이지 기능 구현 시작

**5/23 일요일 회의**
- 마이페이지 기능 구현 마무리
- 상품 추가/수정/삭제 기능 구현 마무리
- DB 테이블 수정
- 회원관리 기능 구현 시작 
- 구매기능, 장바구니 기능 구현 시작
- 메인페이지, HTML+CSS 디자인 시작

**5/26 수요일 회의**
- 회원관리 기능 구현 마무리
- 구매기능, 장바구니 기능 구현 마무리
- DB 테이블 수정
- 메인페이지 디자인 완료, 롤링배너 추가
- 리뷰, 평점기능 구현시작
- 결제시스템, 할인 기능 구현 시작
- 베스트셀러 기능 구현 시작

**5/29 토요일 회의**
- 리뷰, 평점기능 구현 마무리
- 결제 시스템, 할인 기능 구현 마무리
- 베스트셀러 기능 구현 마무리
- DB 테이블 수정
- 코드 리뷰 및 리팩토링
- 매출통계(판매내역) 기능 구현 시작

**5/31 월요일 회의**
- 매출통계(판매내역) 기능 구현 마무리
- 보고서 작성, YouTube 영상 관련 역할분담

**Comment by xx10222** [comment]
회의록 정리 감사합니다!!

**Comment by cjw1359** [comment]
정리 감사합니다

**Comment by justashow** [comment]
프로젝트 끝
